<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Vault\Block\Customer\CreditCards $block */
$tokens = $block->getPaymentTokens();
$viewModel = $block->getViewModel();
?>
<?php if (count($tokens) !== 0): ?>
    <div class="table-wrapper my-credit-cards">
        <table class="data table table-credit-cards" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Stored Payment Methods')) ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col card-number"><?= $block->escapeHtml(__('Card Number')) ?></th>
                <th scope="col" class="col expire"><?= $block->escapeHtml(__('Expiration Date')) ?></th>
                <th scope="col" class="col card-type"><?= $block->escapeHtml(__('Type')) ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($tokens as $token) {
                echo $block->renderTokenHtml($token);
            }
            ?>
            </tbody>
        </table>
    </div>
<?php endif ?>


<?php if (!empty($viewModel->getCustomerSessionId() && $viewModel->checkIsSeller() == false)): ?>
    <?php $buyerResponse = $viewModel->getBuyerDetails(); ?>

    <div class="table-wrapper my-credit-cards">
        <?php if (!empty($buyerResponse) && $buyerResponse['qualificationStatus'] == 'completed'): ?>
            <?php
            $maxCreditLimit = $viewModel->formattedAmount($buyerResponse['qualification']['maxCreditLimit'] ?? '$0.00');
            $creditLimit = $viewModel->formattedAmount($buyerResponse['qualification']['creditLimit'] ?? '$0.00');
            ?>
            <h3><?= /* @noEscape */ $block->escapeHtml(__('Net Terms')) ?></h3>
            <table class="data table table-credit-cards" id="my-orders-table">
                <thead>
                <tr>
                    <th scope="col" class="col card-number">
                        <?= /* @noEscape */ $block->escapeHtml(__('Max Credit Limit')) ?>
                    </th>
                    <th scope="col" class="col expire">
                        <?= /* @noEscape */ $block->escapeHtml(__('Credit Limit')) ?>
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td
                        data-th="<?= /* @noEscape */ $block->escapeHtml(__('Max Credit Limit')) ?>"
                        class="col card-number">
                            <span><?= /* @noEscape */ $maxCreditLimit; ?>
                    </td>
                    <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Credit Limit')) ?>" class="col card-type">
                        <?= /* @noEscape */ $creditLimit; ?>
                    </td>
                </tr>
                </tbody>
            </table>
        <?php endif; ?>

        <?php if (!empty($buyerResponse) && !empty($buyerResponse['paymentData']['creditCards'])): ?>
            <h3><?= /* @noEscape */ $block->escapeHtml(__('Stored Credit Cards')) ?></h3>
            <table class="data table table-credit-cards" id="my-orders-table">
                <thead>
                <tr>
                    <th scope="col" class="col card-number">
                        <?= /* @noEscape */ $block->escapeHtml(__('Card Number')) ?>
                    </th>
                    <th scope="col" class="col expire">
                        <?= /* @noEscape */ $block->escapeHtml(__('Expiration Date')) ?>
                    </th>
                    <th scope="col" class="col card-type">
                        <?= /* @noEscape */ $block->escapeHtml(__('Type')) ?>
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($buyerResponse['paymentData']['creditCards'] as $creditcard):?>
                    <tr>
                        <td
                            data-th="<?= /* @noEscape */ $block->escapeHtml(__('Card Number')) ?>"
                            class="col card-number">
                            <span><?= /* @noEscape */ $block->escapeHtml(__('ending')) ?></span>
                            <?= /* @noEscape */ $creditcard['last4'] ?? ''; ?>
                        </td>
                        <td
                            data-th="<?= /* @noEscape */ $block->escapeHtml(__('Expiration Date')) ?>"
                            class="col card-expire">
                            <?= /* @noEscape */ $creditcard['expiredMonth'].'/'.$creditcard['expiredYear']; ?>
                        </td>
                        <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Type')) ?>" class="col card-type">
                            <?php if ($iconUrl = $viewModel->getCcIconUrl($creditcard['brand'] ?? '')): ?>
                                <img
                                    src="<?= /* @noEscape */ $iconUrl; ?>"
                                    alt="<?= /* @noEscape */ $creditcard['brand'] ?? ''; ?>" />
                            <?php else: ?>
                                <?= /* @noEscape */ "-"; ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        <?php endif; ?>

        <?php if (!empty($buyerResponse) && !empty($buyerResponse['paymentData']['banks'])): ?>
            <h3><?= $block->escapeHtml(__('Stored Bank Accounts')) ?></h3>
            <table class="data table table-credit-cards" id="my-orders-table">
                <caption class="table-caption">
                    <?= /* @noEscape */ $block->escapeHtml(__('Stored Bank Accounts')) ?>
                </caption>
                <thead>
                <tr>
                    <th scope="col" class="col card-number">
                        <?= /* @noEscape */ $block->escapeHtml(__('Institution Name')) ?>
                    </th>
                    <th scope="col" class="col expire">
                        <?= /* @noEscape */ $block->escapeHtml(__('Account Name')) ?>
                    </th>
                    <th scope="col" class="col card-type">
                        <?= /* @noEscape */ $block->escapeHtml(__('Account Number Mask')) ?>
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($buyerResponse['paymentData']['banks'] as $bank):?>
                    <tr>
                        <td
                            data-th="<?= /* @noEscape */ $block->escapeHtml(__('Institution Name')) ?>"
                            class="col card-number">
                            <?= /* @noEscape */ $bank['institutionName'] ?? ''; ?>
                        </td>
                        <td
                            data-th="<?= /* @noEscape */ $block->escapeHtml(__('Account Name')) ?>"
                            class="col card-expire">
                            <?= /* @noEscape */ $bank['accountName']; ?>
                        </td>
                        <td
                            data-th="<?= /* @noEscape */ $block->escapeHtml(__('Account Number Mask')) ?>"
                            class="col card-type">
                            <?= /* @noEscape */ $bank['accountNumberMask'] ?? ''; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        <?php endif; ?>
    </div>
<?php endif; ?>

