<div id="messages">
    <div class="messages">
        <div class="message message-warning warning">
            <div data-ui-id="messages-message-warning">
                <?= $block->escapeHtml(__('To request an Online Credit Memo, open the relevant invoice from the list below,
                and click the ‘Online Credit Memo’ button in the invoice page')); ?>
            </div>
        </div>
    </div>
</div>
