#!/bin/bash

source "$(dirname -- "$0")/common"

if [ ! -d "$CLONE_DIR" ]; then
    echo "Cloning ${CS_GIT_REPO}"
    git clone $CS_GIT_REPO $CLONE_DIR
fi

cd "$CLONE_DIR" || exit
echo "Pulling ${CS_GIT_REPO}"
git pull

echo "Running composer install"
composer install
