<?php
    $vendorIdAvailable = $block->isVendorIdSet();
    $vendorName = 'Balance Vendor Dashboard';
?>

<?php if ($vendorIdAvailable): ?>
    <?php $vendorName = $block->getBalanceVendor(); ?>
    <?php $balancePayStatus = $block->getBalancePayStatus(); ?>
    <div class="balancepay_link">
        <div class="admin__field _required">
            <div class="admin__field-label">
                <label>
                    <span><?php echo __("Balance Vendor"); ?></span>
                </label>
            </div>
            <div class="admin__field-control">
                <a href="<?= $block->getBalancePayDashboardUrl(); ?>" target="_blank"><?php echo __($vendorName);?></a>
                <a class="action action-edit-balance" href="javascript:void(0)" title="Edit Balance Vendor"></a>
            </div>
        </div>
        <div class="admin__field _required">
            <div class="admin__field-label">
                <label>
                    <span><?php echo __("Payouts:"); ?></span>
                </label>
            </div>
            <div class="admin__field-control
            <?php if (strtolower($balancePayStatus) == 'enabled')
                    { echo  'enable'; } else { echo 'disable'; } ?>">
                <?php echo $balancePayStatus; ?>
            </div>
        </div>
    </div>
<?php endif; ?>

<script type="text/javascript">
    require([
            "jquery"
        ],
        function($) {
            "use strict";
            var vendorIdAvailable = '<?php echo $vendorIdAvailable; ?>';
            if (vendorIdAvailable) {
                setTimeout(function () {
                    $('.admin__fieldset').find('[data-index="balance_vendor_id"]').hide();
                },10);
            }
            $(document).ready(function($){
                $('.action-edit-balance').on('click', function(){
                    $('.admin__fieldset').find('[data-index="balance_vendor_id"]').show();
                });
            });
            return;
        });
</script>
<style>
    .balancepay_link {
        width: 100%;
        display: inline-block;
    }
    .balancepay_link .admin__field {
        margin-left: -30px;
        clear:both;
    }

    .balancepay_link .enable {
        color: #fff;
        background: #008000b0;
        max-width: 80px;
        padding: 0 0;
        text-align: center;
        font-weight: 700;
    }
    .balancepay_link .disable {
        color: #fff;
        background: #ea5323;
        max-width: 80px;
        padding: 0 0;
        text-align: center;
        font-weight: 700;
    }


    .balancepay_link .admin__field-label,  .balancepay_link .admin__field-control {
        width: calc( (100%) * .25 - 30px );
        float: left;
        margin-left: 30px;
        line-height: 3.2rem;
    }
    .balancepay_link .admin__field-control a {
        font-weight: bold;
    }
    .action-edit-balance:before{
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        font-size: 18px;
        line-height: 20px;
        color: #757575;
        content: '\e601';
        font-family: 'luma-icons';
        vertical-align: middle;
        display: inline-block;
        font-weight: normal;
        overflow: hidden;
        speak: none;
        text-align: center;
    }
</style>
