<div class="balancepay_link">
    <div class="admin__field _required">
        <div class="admin__field-label">
            <label>
                <span>Balance Vendor</span>
            </label>
        </div>
        <div class="admin__field-control">
            <a href="javascript:void(0)"><?php echo __("Link here");?></a>
            <a class="action action-edit-balance" href="javascript:void(0)" title="Edit Balance Vendor"></a>
        </div>
    </div>
</div>
<style>
    .balancepay_link {
        width: 100%;
        display: inline-block;
    }
    .balancepay_link .admin__field {
        margin-left: -30px;
    }
    .balancepay_link .admin__field-label,  .balancepay_link .admin__field-control {
        width: calc( (100%) * .25 - 30px );
        float: left;
        margin-left: 30px;
    }
    .action-edit-balance:before{
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        font-size: 18px;
        line-height: 20px;
        color: #757575;
        content: '\e601';
        font-family: 'luma-icons';
        vertical-align: middle;
        display: inline-block;
        font-weight: normal;
        overflow: hidden;
        speak: none;
        text-align: center;
    }
</style>
