<?php $vendorIdAvailable = $block->isVendorIdSet(); ?>

<?php if ($vendorIdAvailable): ?>
    <div class="balancepay_link">
        <div class="admin__field _required">
            <div class="admin__field-label">
                <label>
                    <span><?php echo __("Balance Vendor"); ?></span>
                </label>
            </div>
            <div class="admin__field-control">
                <a href="<?= $block->getBalancePayDashboardUrl(); ?>" target="_blank"><?php echo __("Balance Vendor Dashboard");?></a>
                <a class="action action-edit-balance" href="javascript:void(0)" title="Edit Balance Vendor"></a>
            </div>
        </div>
    </div>
<?php endif; ?>

<script type="text/javascript">
    require([
            "jquery"
        ],
        function($) {
            "use strict";

            var vendorIdAvailable = '<?php echo $vendorIdAvailable; ?>';
            if (vendorIdAvailable) {
                setTimeout(function () {
                    $('.admin__fieldset').find('[data-index="balance_vendor_id"]').hide();
                },10);
            }
            $(document).ready(function($){
                $('.action-edit-balance').on('click', function(){
                    $('.admin__fieldset').find('[data-index="balance_vendor_id"]').show();
                });
            });
            return;
        });
</script>
<style>
    .balancepay_link {
        width: 100%;
        display: inline-block;
    }
    .balancepay_link .admin__field {
        margin-left: -30px;
    }
    .balancepay_link .admin__field-label,  .balancepay_link .admin__field-control {
        width: calc( (100%) * .25 - 30px );
        float: left;
        margin-left: 30px;
    }
    .balancepay_link .admin__field-control a {
        font-weight: bold;
    }
    .action-edit-balance:before{
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        font-size: 18px;
        line-height: 20px;
        color: #757575;
        content: '\e601';
        font-family: 'luma-icons';
        vertical-align: middle;
        display: inline-block;
        font-weight: normal;
        overflow: hidden;
        speak: none;
        text-align: center;
    }
</style>
